### ISSUE TITLE
MVP To-do List

### ISSUE THREAD

**Issue by MikeVezina** [MikeVezina/epistemic-agents#9]
## Model Creation
- [ ] Generate a list of propositions
- [ ] Generate worlds with respective true propositions
- [ ] Generate accessibility/indisting. using perceptions or additional beliefs

### Logic Translation
The epistemic reasoner does not allow for parentheses in the proposition names. If we want to utilize Jason literals (i.e. `alice(aa)`) as propositions, then there has to be a conversion from Jason literals to propositions.

Special characters such as `alice[aa]`, `alice{aa}`, `alice_aa`, `alice-aa` could be appropriate replacements.
